import { Body, Controller, Get, Param, Patch, Post, Query, Res } from '@nestjs/common';
import type { Response } from 'express';
import type { z } from 'zod';
import {
  createVoucherSchema,
  finCreateAccountSchema,
  finDateRangeQuery,
  finExportQuery,
  finStatementQuery,
  finUpdateAccountSchema,
  ledgerKpiQuery,
  lockBooksSchema,
  reverseVoucherSchema,
  voucherListQuery,
  type CreateVoucherInput,
  type VoucherListQuery,
} from '@lexisora/shared';
import { Ctx, hasPerm, RequirePerm } from '../../core/auth/decorators';
import type { RequestContext } from '../../core/context/request-context';
import { ZodPipe } from '../../core/http/zod.pipe';
import { forbidden } from '../../core/http/errors';
import { LedgerService } from './ledger.service';
import { dateOnly } from './lib/money';

/** Send generated bytes (CSV / PDF) as a download or inline. */
export function sendBytes(res: Response, data: Buffer | string, filename: string, mime: string, inline = false) {
  res.setHeader('Content-Type', mime);
  res.setHeader('Content-Disposition', `${inline ? 'inline' : 'attachment'}; filename="${filename.replace(/["\r\n]/g, '')}"`);
  res.setHeader('Cache-Control', 'private, no-store');
  res.send(data);
}

/**
 * Ledger (spec-workfin Module I): month KPIs, day book / income / expense lines / HR vouchers,
 * trial balance, CSV export, ledger options for the voucher form and period lock.
 * HR holding only `ledger.hrvoucher` sees and raises HR vouchers (D23).
 */
@Controller('ledger')
export class LedgerController {
  constructor(private readonly ledger: LedgerService) {}

  @Get('kpis')
  @RequirePerm('ledger.manage')
  kpis(@Query(new ZodPipe(ledgerKpiQuery)) q: z.infer<typeof ledgerKpiQuery>) {
    return this.ledger.kpis(q.month);
  }

  @Get('vouchers')
  @RequirePerm('ledger.manage', 'ledger.hrvoucher')
  vouchers(@Query(new ZodPipe(voucherListQuery)) q: VoucherListQuery, @Ctx() ctx: RequestContext) {
    return this.ledger.list(q, ctx);
  }

  @Get('options')
  @RequirePerm('ledger.manage', 'ledger.hrvoucher')
  options(@Ctx() ctx: RequestContext) {
    return this.ledger.ledgerOptions(ctx);
  }

  @Get('trial-balance')
  @RequirePerm('ledger.manage')
  trialBalance(@Query(new ZodPipe(finDateRangeQuery)) q: z.infer<typeof finDateRangeQuery>) {
    return this.ledger.trialBalance(q.from, q.to);
  }

  @Get('export')
  @RequirePerm('ledger.manage', 'ledger.hrvoucher')
  async export(@Query(new ZodPipe(finExportQuery)) q: z.infer<typeof finExportQuery>, @Ctx() ctx: RequestContext, @Res() res: Response) {
    if (q.kind === 'trial' && !hasPerm(ctx, 'ledger.manage')) throw forbidden();
    const f = await this.ledger.exportCsv(q.kind, q.from, q.to, ctx);
    sendBytes(res, `﻿${f.csv}`, f.filename, 'text/csv; charset=utf-8');
  }

  @Post('lock')
  @RequirePerm('ledger.manage')
  lock(@Body(new ZodPipe(lockBooksSchema)) dto: z.infer<typeof lockBooksSchema>) {
    return this.ledger.lockBooks(dto.upTo);
  }

  @Get('settings')
  @RequirePerm('ledger.manage', 'invoices.manage')
  async settings() {
    const s = await this.ledger.financeSettings();
    return { booksLockedUpTo: s.booksLockedUpTo, defaultPaymentTermsDays: s.defaultPaymentTermsDays, bank: s.bank, signatory: s.signatory };
  }
}

@Controller('vouchers')
export class VouchersController {
  constructor(private readonly ledger: LedgerService) {}

  @Post()
  @RequirePerm('ledger.manage', 'ledger.hrvoucher')
  create(@Body(new ZodPipe(createVoucherSchema)) dto: CreateVoucherInput, @Ctx() ctx: RequestContext) {
    return this.ledger.createManual(dto, ctx);
  }

  @Get(':id')
  @RequirePerm('ledger.manage', 'ledger.hrvoucher')
  detail(@Param('id') id: string, @Ctx() ctx: RequestContext) {
    return this.ledger.detail(id, ctx);
  }

  @Post(':id/reverse')
  @RequirePerm('ledger.manage')
  async reverse(@Param('id') id: string, @Body(new ZodPipe(reverseVoucherSchema)) dto: z.infer<typeof reverseVoucherSchema>) {
    const v = await this.ledger.reverse(id, dto.reason);
    return { id: v.id, number: v.number };
  }
}

@Controller('accounts')
export class AccountsController {
  constructor(private readonly ledger: LedgerService) {}

  @Get()
  @RequirePerm('ledger.manage', 'purchases.manage')
  list() {
    return this.ledger.accounts();
  }

  @Post()
  @RequirePerm('ledger.manage')
  create(@Body(new ZodPipe(finCreateAccountSchema)) dto: z.infer<typeof finCreateAccountSchema>) {
    return this.ledger.createAccount(dto);
  }

  @Patch(':id')
  @RequirePerm('ledger.manage')
  update(@Param('id') id: string, @Body(new ZodPipe(finUpdateAccountSchema)) dto: z.infer<typeof finUpdateAccountSchema>) {
    return this.ledger.updateAccount(id, dto);
  }

  @Get(':id/statement')
  @RequirePerm('ledger.manage')
  statement(@Param('id') id: string, @Query(new ZodPipe(finStatementQuery)) q: z.infer<typeof finStatementQuery>) {
    if (q.from && q.to && dateOnly(q.from) > dateOnly(q.to)) return this.ledger.statement(id, q.to, q.from);
    return this.ledger.statement(id, q.from, q.to);
  }
}
