import type { Prisma, PrismaClient } from '@prisma/client';
import PDFDocument from 'pdfkit';
import { createHash, randomUUID } from 'node:crypto';
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import type { SeedCtx } from './core';
import { CryptoService } from '../../src/core/crypto/crypto.service';
import { EXIT_CHECKLIST, computeLwd, defaultNoticeDays, maskPan } from '../../src/modules/people/people.rules';

/**
 * Demo data for the people domain (core release): Priya's digital vault rows exactly as the
 * wireframe shows them, statutory/bank details for the demo cast, Ananya's open exit case
 * (notice period) and Meera's paperless onboarding in progress (offer signed, NDA next).
 */

const d = (s: string) => new Date(`${s}T00:00:00.000Z`);
const at = (s: string, hm = '10:00') => new Date(`${s}T${hm}:00+05:30`);

function pdf(title: string, lines: string[]): Promise<Buffer> {
  return new Promise((res, rej) => {
    const doc = new PDFDocument({ size: 'A4', margin: 56 });
    const chunks: Buffer[] = [];
    doc.on('data', (c: Buffer) => chunks.push(c));
    doc.on('end', () => res(Buffer.concat(chunks)));
    doc.on('error', rej);
    doc.font('Helvetica-Bold').fontSize(9).fillColor('#8a6d3b').text('LEXISORA INFOTECH PVT. LTD.', { characterSpacing: 1.5 });
    doc.moveDown(0.6).font('Times-Roman').fontSize(22).fillColor('#1b1b1b').text(title);
    doc.moveDown(0.8).font('Helvetica').fontSize(10.5).fillColor('#333');
    for (const l of lines) doc.text(l, { align: 'justify' }).moveDown(0.5);
    doc.moveDown(2).fontSize(8).fillColor('#888').text('Demo document generated by the Lexisora HRMS seed.');
    doc.end();
  });
}

export async function seed_people(prisma: PrismaClient, ctx: SeedCtx): Promise<void> {
  const { tenantId, emp, user } = ctx;
  const crypto = new CryptoService();
  const storageRoot = resolve(process.env.STORAGE_DIR || './storage');
  const hrName = 'Kavya Iyer';
  const hrUser = user.kavya ?? null;

  async function file(ownerKey: string, name: string, title: string, lines: string[], createdAt: Date) {
    const buf = await pdf(title, lines);
    const key = `${tenantId}/vault/${randomUUID()}-${name}`;
    const path = join(storageRoot, key);
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, buf);
    const row = await prisma.fileObject.create({
      data: { tenantId, ownerUserId: user[ownerKey] ?? null, storageKey: key, filename: name, mime: 'application/pdf', size: buf.length, sha256: createHash('sha256').update(buf).digest('hex'), category: 'vault', isPrivate: true, createdAt },
    });
    return { id: row.id, sha256: row.sha256! };
  }

  type DocSeed = {
    who: string;
    category: Prisma.EmployeeDocumentUncheckedCreateInput['category'];
    docType: Prisma.EmployeeDocumentUncheckedCreateInput['docType'];
    title: string;
    source: Prisma.EmployeeDocumentUncheckedCreateInput['source'];
    status: Prisma.EmployeeDocumentUncheckedCreateInput['verificationStatus'];
    uploaded: string;
    lines: string[];
  };
  async function doc(s: DocSeed) {
    if (!emp[s.who]) return null;
    const up = at(s.uploaded);
    const f = await file(s.who, `${s.title.toLowerCase().replace(/[^a-z0-9]+/g, '-')}.pdf`, s.title, s.lines, up);
    const verified = s.status === 'VERIFIED';
    const row = await prisma.employeeDocument.create({
      data: {
        tenantId,
        employeeId: emp[s.who]!,
        category: s.category,
        docType: s.docType,
        title: s.title,
        fileId: f.id,
        source: s.source,
        verificationStatus: s.status,
        verifiedByUserId: verified ? hrUser : null,
        verifiedByName: verified ? hrName : null,
        verifiedAt: verified ? new Date(up.getTime() + 2 * 86400_000) : null,
        uploadedAt: up,
        uploadedByUserId: s.source === 'SELF_UPLOAD' || s.source === 'ESIGNED' ? (user[s.who] ?? null) : hrUser,
        createdAt: up,
        tags: [],
      },
    });
    return { row, sha256: f.sha256 };
  }

  // ── Priya Sharma — "My digital vault" + profile Documents tab (wireframe rows) ──
  const P = 'Priya Sharma';
  const priyaDocs: DocSeed[] = [
    { who: 'priya', category: 'OFFER_COMPENSATION', docType: 'OFFER_LETTER', title: 'Offer letter', source: 'ESIGNED', status: 'NOT_REQUIRED', uploaded: '2024-01-12', lines: [`Dear ${P},`, 'This letter confirms your appointment at Lexisora Infotech as Software Engineer in the Development department with the compensation shown in Annexure A.', `Signed electronically by ${P} on 12 Jan 2024 · audit trail on file.`] },
    { who: 'priya', category: 'LEGAL', docType: 'NDA', title: 'NDA', source: 'ESIGNED', status: 'NOT_REQUIRED', uploaded: '2024-01-12', lines: ['You agree to keep client code, data and business information confidential during and after employment.', `Signed electronically by ${P} on 12 Jan 2024.`] },
    { who: 'priya', category: 'OFFER_COMPENSATION', docType: 'COMPENSATION_BREAKDOWN', title: 'Compensation breakdown', source: 'GENERATED', status: 'NOT_REQUIRED', uploaded: '2026-04-01', lines: ['Effective 1 Apr 2026.', 'Basic ₹ 42,000 · HRA ₹ 21,000 · Special allowance ₹ 21,000 · PF (employer) ₹ 1,800.', 'Monthly CTC ₹ 85,800 · Annual CTC ₹ 10,29,600.'] },
    { who: 'priya', category: 'GOVERNMENT_ID', docType: 'PAN', title: 'PAN card', source: 'SELF_UPLOAD', status: 'VERIFIED', uploaded: '2024-01-12', lines: ['Permanent Account Number card (scan).', 'Name: PRIYA SHARMA'] },
    { who: 'priya', category: 'GOVERNMENT_ID', docType: 'AADHAAR', title: 'Aadhaar card', source: 'SELF_UPLOAD', status: 'VERIFIED', uploaded: '2024-01-12', lines: ['Aadhaar card (scan, masked).', 'XXXX XXXX 4821'] },
    { who: 'priya', category: 'EDUCATION', docType: 'DEGREE', title: 'B.Tech marksheets', source: 'SELF_UPLOAD', status: 'PENDING', uploaded: '2024-01-14', lines: ['B.Tech (Computer Engineering) — semester marksheets 1–8.', 'Gujarat Technological University, 2019.'] },
    { who: 'priya', category: 'CAREER', docType: 'RESUME', title: 'Resume', source: 'RECRUITMENT', status: 'NOT_REQUIRED', uploaded: '2024-01-10', lines: [`${P} — Software Engineer`, 'React, Node.js, PostgreSQL. 4 years building SaaS products.'] },
  ];
  for (const s of priyaDocs) await doc(s);

  // A few more so HR's verification queue and other profiles look real.
  const others: DocSeed[] = [
    { who: 'rahul', category: 'GOVERNMENT_ID', docType: 'PAN', title: 'PAN card', source: 'SELF_UPLOAD', status: 'VERIFIED', uploaded: '2023-02-20', lines: ['PAN card (scan).'] },
    { who: 'rahul', category: 'GOVERNMENT_ID', docType: 'AADHAAR', title: 'Aadhaar card', source: 'SELF_UPLOAD', status: 'VERIFIED', uploaded: '2023-02-20', lines: ['Aadhaar card (scan, masked).'] },
    { who: 'vikram', category: 'EMPLOYMENT', docType: 'RELIEVING_LETTER', title: 'Relieving letter · previous employer', source: 'SELF_UPLOAD', status: 'PENDING', uploaded: '2026-09-24', lines: ['Relieving letter from previous employer.'] },
    { who: 'isha', category: 'GOVERNMENT_ID', docType: 'AADHAAR', title: 'Aadhaar card', source: 'SELF_UPLOAD', status: 'PENDING', uploaded: '2026-09-15', lines: ['Aadhaar card (scan, masked).'] },
    { who: 'isha', category: 'EDUCATION', docType: 'MARKSHEET_12', title: '12th marksheet', source: 'SELF_UPLOAD', status: 'VERIFIED', uploaded: '2026-09-15', lines: ['Higher secondary marksheet.'] },
  ];
  for (const s of others) await doc(s);

  // Statutory & bank details (encrypted at rest; masked on screen).
  const stat: Record<string, { pan: string; aadhaar: string; acct: string; ifsc: string; bank: string; uan?: string; tshirt?: string }> = {
    priya: { pan: 'BKLPS4821K', aadhaar: '234567894821', acct: '50100248170417', ifsc: 'HDFC0000240', bank: 'HDFC Bank', uan: '101874563210', tshirt: 'M' },
    rahul: { pan: 'AQWPD1182M', aadhaar: '345678901118', acct: '000401562233', ifsc: 'ICIC0000004', bank: 'ICICI Bank', uan: '101874563118', tshirt: 'L' },
    neha: { pan: 'AJKPK2020N', aadhaar: '456789012020', acct: '37105540020', ifsc: 'SBIN0001043', bank: 'State Bank of India', uan: '101874560020', tshirt: 'S' },
  };
  for (const [k, s] of Object.entries(stat)) {
    if (!emp[k]) continue;
    await prisma.employee.update({
      where: { id: emp[k] },
      data: {
        panEnc: crypto.encrypt(s.pan),
        aadhaarEnc: crypto.encrypt(s.aadhaar),
        aadhaarLast4: s.aadhaar.slice(-4),
        bankAccountEnc: crypto.encrypt(s.acct),
        bankAccountLast4: s.acct.slice(-4),
        bankIfsc: s.ifsc,
        bankName: s.bank,
        uan: s.uan ?? null,
        tshirtSize: s.tshirt ?? null,
        taxRegime: 'NEW',
      },
    });
  }

  // ── Ananya Rao — notice period with an open exit checklist ──
  if (emp.ananya) {
    const resignation = '2026-09-10';
    const e = await prisma.employee.findUnique({ where: { id: emp.ananya }, select: { joiningDate: true, employmentType: true } });
    const notice = defaultNoticeDays((e?.employmentType ?? 'FULL_TIME') as never, e?.joiningDate?.toISOString().slice(0, 10) ?? null, '2026-09-29');
    const lwd = computeLwd(resignation, notice, null);
    await prisma.exitCase.create({
      data: {
        tenantId,
        employeeId: emp.ananya,
        exitType: 'RESIGNATION',
        resignationDate: d(resignation),
        lastWorkingDay: d(lwd.lastWorkingDay),
        noticeShortfallDays: lwd.shortfallDays,
        reason: 'Relocating to Bengaluru for family reasons.',
        createdAt: at(resignation, '11:30'),
        items: {
          create: EXIT_CHECKLIST.map((c, i) => ({
            tenantId,
            key: c.key,
            label: c.label,
            ownerRole: c.ownerRole,
            blocking: c.blocking,
            auto: c.auto,
            order: i,
            status: c.key === 'ASSET_RETURN' || c.key === 'EXIT_INTERVIEW' ? 'DONE' : 'PENDING',
            doneByName: c.key === 'EXIT_INTERVIEW' ? hrName : null,
            doneAt: c.key === 'EXIT_INTERVIEW' ? at('2026-09-18', '15:00') : null,
          })),
        },
      },
    });
    await prisma.employee.update({ where: { id: emp.ananya }, data: { noticeStartDate: d(resignation), exitDate: d(lwd.lastWorkingDay), exitReason: 'Relocating to Bengaluru for family reasons.' } });
  }

  // ── Meera Iyer — paperless onboarding in progress (joins Tue 6 Oct 2026) ──
  if (emp.meera) {
    const signed = await doc({
      who: 'meera',
      category: 'OFFER_COMPENSATION',
      docType: 'OFFER_LETTER',
      title: 'Offer letter',
      source: 'ESIGNED',
      status: 'NOT_REQUIRED',
      uploaded: '2026-09-24',
      lines: ['Dear Meera Iyer,', 'This letter confirms your appointment at Lexisora Infotech as QA Engineer in the QA department, joining on 6 Oct 2026, with the compensation shown in Annexure A.', 'Signed electronically by Meera Iyer on 24 Sep 2026 · IP 49.36.112.18.'],
    });
    const steps = [
      { key: 'offer', status: 'DONE' as const, completedAt: at('2026-09-24', '19:42'), data: { signedAt: at('2026-09-24', '19:42').toISOString(), signedSha256: signed?.sha256 ?? null } },
      { key: 'nda', status: 'PENDING' as const },
      { key: 'docs', status: 'PENDING' as const },
      { key: 'bank', status: 'PENDING' as const },
      { key: 'kit', status: 'PENDING' as const },
    ];
    await prisma.onboarding.create({
      data: {
        tenantId,
        employeeId: emp.meera,
        status: 'IN_PROGRESS',
        invitedAt: at('2026-09-22', '11:05'),
        startedAt: at('2026-09-24', '19:30'),
        createdAt: at('2026-09-22', '11:00'),
        steps: {
          create: steps.map((s, i) => ({
            tenantId,
            key: s.key,
            order: i + 1,
            status: s.status,
            completedAt: 'completedAt' in s ? s.completedAt : null,
            data: 'data' in s ? (s.data as Prisma.InputJsonValue) : undefined,
          })),
        },
      },
    });
    // Invite link for the demo (Mailpit shows the real one when HR clicks "Resend invite").
    if (user.meera) await prisma.user.update({ where: { id: user.meera }, data: { inviteToken: 'demo-meera-invite-token', inviteExpiresAt: new Date('2026-10-13T00:00:00.000Z') } });
  }

  ctx.extra.people = { priyaPanMasked: maskPan(stat.priya!.pan) };
}
