import type { Prisma, PrismaClient } from '@prisma/client';
import PDFDocument from 'pdfkit';
import { createHash, randomUUID } from 'node:crypto';
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { quoteIndexFor, type WpAudienceRule } from '@lexisora/shared';
import type { SeedCtx } from './core';
import { projectIdsByEmployee, resolveAudience, type AudienceSubject } from '../../src/modules/workplace/common/audience.rules';
import { excerptOf, sanitizeHtml } from '../../src/modules/workplace/common/html';

/**
 * Demo data for the workplace domain — core release ("today" = Tue 29 Sep 2026, IST):
 *  - Thought of the day: the wireframe's 4 QUOTES plus a curated pool, ordered so that the
 *    rotation shows "Do the hard thing first…" on 29 Sep (the wireframe's pick for that date).
 *  - Notice board: the 4 wireframe rows with materialised read receipts (Diwali potluck with a
 *    sign-up sheet attachment, Atlas CRM release freeze → Development · Atlas, travel
 *    reimbursement, QA regression schedule → QA Team) plus one HR draft. Recipient counts are
 *    computed from the real audience (13-person demo tenant), so "112 / 128" becomes "10 / 11".
 *  - Company events: Town hall 3 Oct 5 pm (dashboard), Security awareness training, Diwali.
 *    Birthdays/anniversaries come from core Employee rows (Rahul 30 Sep, Sneha 3 years 2 Oct).
 *  - Policies (minimal, feeds the dashboard "Acknowledge … update" to-do): the 5 wireframe
 *    documents; everyone acknowledged except the Leave & attendance policy update for Priya
 *    and a few others (due today).
 *  - Personal to-dos for the sign-in personas.
 * Reads people/work rows defensively: works when the work seed (projects) is absent.
 */

const TODAY = '2026-09-29';
const d = (k: string) => new Date(`${k}T00:00:00.000Z`);
const at = (k: string, hm = '10:00') => new Date(`${k}T${hm}:00+05:30`);
const addMin = (t: Date, m: number) => new Date(t.getTime() + m * 60_000);
const NOW = at(TODAY, '09:40');

/** The wireframe's QUOTES (web-app.html L857), in order. */
export const WIREFRAME_QUOTES = [
  'Small steps every day add up to big results.',
  'Do the hard thing first; the rest of the day gets lighter.',
  'Quality is never an accident.',
  'You are one focused hour away from a good day.',
];

const CURATED_QUOTES: [string, string | null][] = [
  ['Well begun is half done.', 'Aristotle'],
  ['The secret of getting ahead is getting started.', 'Mark Twain'],
  ['Simplicity is prerequisite for reliability.', 'Edsger W. Dijkstra'],
  ['Well done is better than well said.', 'Benjamin Franklin'],
  ['It always seems impossible until it’s done.', 'Nelson Mandela'],
  ['Make it work, make it right, make it fast.', 'Kent Beck'],
  ['The best way to predict the future is to invent it.', 'Alan Kay'],
  ['Arise, awake, and stop not till the goal is reached.', 'Swami Vivekananda'],
  ['Excellence is a continuous process and not an accident.', 'A. P. J. Abdul Kalam'],
  ['First, solve the problem. Then, write the code.', 'John Johnson'],
  ['Programs must be written for people to read, and only incidentally for machines to execute.', 'Harold Abelson'],
  ['Alone we can do so little; together we can do so much.', 'Helen Keller'],
  ['Start where you are. Use what you have. Do what you can.', 'Arthur Ashe'],
  ['Don’t watch the clock; do what it does. Keep going.', 'Sam Levenson'],
  ['If you want to go fast, go alone. If you want to go far, go together.', 'African proverb'],
  ['Focus on being productive instead of busy.', 'Tim Ferriss'],
  ['Done is better than perfect.', null],
  ['Ask for help early; it is a sign of a strong team, not a weak one.', null],
];

function pdf(kicker: string, title: string, lines: string[]): Promise<Buffer> {
  return new Promise((res, rej) => {
    const doc = new PDFDocument({ size: 'A4', margin: 56 });
    const chunks: Buffer[] = [];
    doc.on('data', (c: Buffer) => chunks.push(c));
    doc.on('end', () => res(Buffer.concat(chunks)));
    doc.on('error', rej);
    doc.font('Helvetica-Bold').fontSize(9).fillColor('#8a6d3b').text(kicker.toUpperCase(), { characterSpacing: 1.5 });
    doc.moveDown(0.6).font('Times-Roman').fontSize(22).fillColor('#1b1b1b').text(title);
    doc.moveDown(0.8).font('Helvetica').fontSize(10.5).fillColor('#333');
    for (const l of lines) doc.text(l, { align: 'left' }).moveDown(0.5);
    doc.moveDown(2).fontSize(8).fillColor('#888').text('Lexisora Infotech Pvt. Ltd. · Demo document generated by the Lexisora HRMS seed.');
    doc.end();
  });
}

type Pop = AudienceSubject & { userId: string | null; joiningDate: Date | null };

export async function seed_workplace(prisma: PrismaClient, ctx: SeedCtx): Promise<void> {
  const { tenantId, emp, user, dept } = ctx;
  const E = (k: string): string | null => emp[k] ?? null;
  const storageRoot = resolve(process.env.STORAGE_DIR || './storage');

  /** Mirrors StorageService.save for seed-time documents. */
  async function file(ownerKey: string, name: string, category: string, isPrivate: boolean, buf: Buffer, createdAt: Date) {
    const key = `${tenantId}/${category}/${createdAt.toISOString().slice(0, 7)}/${randomUUID()}-${name.replace(/[^\w.\- ]+/g, '_')}`;
    const path = join(storageRoot, key);
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, buf);
    const row = await prisma.fileObject.create({
      data: { tenantId, ownerUserId: user[ownerKey] ?? null, storageKey: key, filename: name, mime: 'application/pdf', size: buf.length, sha256: createHash('sha256').update(buf).digest('hex'), category, isPrivate, createdAt },
    });
    return row;
  }

  // ── Audience population (ACTIVE / NOTICE_PERIOD employees + project membership) ──
  const people = await prisma.employee.findMany({
    where: { tenantId, status: { in: ['ACTIVE', 'NOTICE_PERIOD'] } },
    select: { id: true, userId: true, departmentId: true, branchId: true, employmentType: true, joiningDate: true },
    orderBy: { empCode: 'asc' },
  });
  const [members, projects] = await Promise.all([
    prisma.projectMember.findMany({ where: { tenantId }, select: { projectId: true, employeeId: true } }).catch(() => []),
    prisma.project.findMany({ where: { tenantId }, select: { id: true, key: true, leadEmployeeId: true } }).catch(() => []),
  ]);
  const byEmp = projectIdsByEmployee(members, projects);
  const pop: Pop[] = people.map((p) => ({ ...p, projectIds: [...(byEmp.get(p.id) ?? [])] }));
  const atlasId: string | null = ctx.extra?.projects?.AT ?? projects.find((p) => p.key === 'AT')?.id ?? null;

  await seedQuotes(prisma, tenantId);
  await seedEvents(prisma, tenantId, E);
  await seedNotices();
  await seedPolicies();
  await seedTodos(prisma, tenantId, E);

  // ── Notice board ─────────────────────────────────────────────────────────
  async function seedNotices() {
    type NoticeSeed = {
      title: string;
      html: string;
      visibility: 'GLOBAL' | 'TEAM';
      author: string;
      audiences: WpAudienceRule[];
      status: 'PUBLISHED' | 'DRAFT';
      publishedAt?: Date;
      /** Persona keys who have not opened it yet; every other recipient has read it. */
      unread?: string[];
      email?: boolean;
      pinned?: boolean;
      attachment?: { name: string; title: string; lines: string[] };
    };
    const rules: { dev: WpAudienceRule[]; qa: WpAudienceRule[] } = {
      dev: [
        ...(dept.Development ? [{ type: 'DEPARTMENT' as const, refId: dept.Development, label: 'Development' }] : []),
        ...(atlasId ? [{ type: 'PROJECT' as const, refId: atlasId, label: 'Atlas' }] : []),
      ],
      qa: dept.QA ? [{ type: 'DEPARTMENT', refId: dept.QA, label: 'QA Team' }] : [],
    };
    const rows: NoticeSeed[] = [
      {
        title: 'Diwali celebration & potluck',
        html: '<p><strong>8 Nov, 4 pm onwards on the terrace.</strong> Sign up for a dish by 1 Nov.</p>',
        visibility: 'GLOBAL',
        author: 'kavya',
        audiences: [],
        status: 'PUBLISHED',
        publishedAt: at('2026-09-27', '11:30'),
        unread: ['priya'],
        email: true,
        attachment: {
          name: 'Diwali potluck sign-up sheet.pdf',
          title: 'Diwali celebration & potluck',
          lines: [
            'Sunday, 8 November 2026 · 4 pm onwards · Terrace, Ahmedabad HQ (Pune office: Baner Road cafeteria).',
            'Families are welcome. Please sign up for one dish (starter, main, dessert or drinks) with HR by 1 November so we avoid duplicates.',
            'Rangoli competition at 5 pm — teams of up to four. Diyas and colours are provided by the office.',
            'Contact: Kavya Iyer (HR) · hr@lexisora.com',
          ],
        },
      },
      {
        title: 'Atlas CRM release freeze',
        html: '<p>Merges close Wednesday EOD.</p>',
        visibility: 'TEAM',
        author: 'arjun',
        audiences: rules.dev,
        status: 'PUBLISHED',
        publishedAt: at('2026-09-26', '16:00'),
        unread: ['isha'],
      },
      {
        title: 'Revised travel reimbursement',
        html: '<p>New per-km rates apply from 1 October.</p>',
        visibility: 'GLOBAL',
        author: 'kavya',
        audiences: [],
        status: 'PUBLISHED',
        publishedAt: at('2026-09-22', '11:00'),
        unread: ['isha', 'karan', 'divya'],
        email: true,
      },
      {
        title: 'QA regression schedule',
        html: '<p>Billing regression runs Thursday and Friday. Keep the QA environment free of deployments until sign-off.</p>',
        visibility: 'TEAM',
        author: 'sneha',
        audiences: rules.qa,
        status: 'PUBLISHED',
        publishedAt: at('2026-09-20', '10:00'),
      },
      {
        title: 'Appraisal cycle 2026: timelines',
        html:
          '<h2>What happens when</h2><ul><li><strong>1 Oct</strong> — self reviews open</li><li><strong>15 Oct</strong> — manager reviews</li><li><strong>31 Oct</strong> — calibration and letters</li></ul><p>The new KRA template is on the Company feed.</p>',
        visibility: 'GLOBAL',
        author: 'kavya',
        audiences: [],
        status: 'DRAFT',
      },
    ];
    const cutoff = at(TODAY, '09:30');
    for (const n of rows) {
      const authorId = E(n.author);
      if (!authorId) continue;
      if (n.visibility === 'TEAM' && !n.audiences.length) continue; // department missing — nothing to address
      const bodyHtml = sanitizeHtml(n.html);
      const created = n.publishedAt ? addMin(n.publishedAt, -45) : at('2026-09-28', '17:10');
      const notice = await prisma.notice.create({
        data: {
          tenantId,
          title: n.title,
          bodyHtml,
          excerpt: excerptOf(bodyHtml, 300),
          visibility: n.visibility,
          status: n.status,
          authorEmployeeId: authorId,
          audiences: n.audiences as Prisma.InputJsonValue,
          publishedAt: n.publishedAt ?? null,
          pinned: n.pinned ?? false,
          emailRecipients: n.email ?? n.visibility === 'GLOBAL',
          createdAt: created,
        },
      });
      if (n.attachment) {
        const buf = await pdf('Lexisora Infotech · Notice', n.attachment.title, n.attachment.lines);
        const f = await file(n.author, n.attachment.name, 'notice', true, buf, created);
        await prisma.noticeAttachment.create({ data: { tenantId, noticeId: notice.id, fileId: f.id, name: f.filename, sizeBytes: f.size, mime: f.mime } });
      }
      if (n.status !== 'PUBLISHED' || !n.publishedAt) continue;
      const ruleSet: WpAudienceRule[] = n.visibility === 'GLOBAL' ? [{ type: 'ALL' }] : n.audiences;
      const ids = resolveAudience(pop, ruleSet).filter((id) => id !== authorId);
      const unread = new Set((n.unread ?? []).map(E).filter((x): x is string => !!x));
      const recips = ids.map((id, i) => {
        const p = pop.find((x) => x.id === id)!;
        const readAt = unread.has(id) ? null : addMin(n.publishedAt!, 18 + i * 53);
        return { tenantId, noticeId: notice.id, employeeId: id, userId: p.userId, addedAt: n.publishedAt!, readAt: readAt && readAt < cutoff ? readAt : readAt ? addMin(cutoff, -(i + 1) * 7) : null };
      });
      if (recips.length) await prisma.noticeRecipient.createMany({ data: recips });
      await prisma.notice.update({ where: { id: notice.id }, data: { recipientCount: recips.length, readCount: recips.filter((r) => r.readAt).length } });
    }
  }

  // ── Policies (only what the dashboard's acknowledgement to-do needs; the Policies
  //    screen ships in the next workplace release and builds on these rows) ──────────
  async function seedPolicies() {
    const hr = 'kavya';
    type PolicySeed = {
      title: string;
      category: string;
      requiresAck: boolean;
      holidayYear?: number;
      versions: { version: number; effectiveFrom: string; publishedAt: Date; summary?: string; lines: string[]; ackDueAt?: Date; pending?: string[] }[];
    };
    const policies: PolicySeed[] = [
      {
        title: 'Employee handbook 2026',
        category: 'HANDBOOK',
        requiresAck: true,
        versions: [
          {
            version: 1,
            effectiveFrom: '2026-04-01',
            publishedAt: at('2026-04-01', '10:00'),
            lines: ['Our values, code of conduct, working hours, dress code, communication norms and the escalation matrix.', 'Every employee acknowledges the handbook on joining and on each annual revision.'],
          },
        ],
      },
      {
        title: 'Leave & attendance policy',
        category: 'LEAVE_ATTENDANCE',
        requiresAck: true,
        versions: [
          { version: 1, effectiveFrom: '2025-04-01', publishedAt: at('2025-04-01', '10:00'), lines: ['Leave types, accrual, carry forward, attendance rules and regularisation.'] },
          {
            version: 2,
            effectiveFrom: '2026-07-15',
            publishedAt: at('2026-07-15', '10:00'),
            summary: 'Comp-off must be availed within 60 days; missed punches are regularised within 3 working days.',
            lines: [
              'Earned leave accrues monthly (1.25 days) and up to 15 days carry forward; casual and sick leave lapse at year end.',
              'Comp-off earned on a weekly off or holiday must be availed within 60 days.',
              'A missed punch must be regularised within 3 working days, with your manager’s approval.',
              'Remote and hybrid staff punch on the web or desktop app; office staff use the biometric sensor.',
            ],
            // HR extended the acknowledgement deadline for this update to today (reminder sent 22 Sep).
            ackDueAt: at(TODAY, '18:30'),
            pending: ['priya', 'rahul', 'isha', 'karan', 'divya'],
          },
        ],
      },
      {
        title: 'Holiday list 2026',
        category: 'HOLIDAY_LIST',
        requiresAck: false,
        holidayYear: 2026,
        versions: [{ version: 1, effectiveFrom: '2026-01-01', publishedAt: at('2026-01-01', '10:00'), lines: ['Mandatory and optional holidays for 2026 for the Ahmedabad and Pune offices.'] }],
      },
      {
        title: 'IT & data security policy',
        category: 'IT_SECURITY',
        requiresAck: true,
        versions: [
          {
            version: 1,
            effectiveFrom: '2026-03-10',
            publishedAt: at('2026-03-10', '10:00'),
            lines: ['Acceptable use of laptops and accounts, password and MFA rules, client data handling, removable media and incident reporting.'],
          },
        ],
      },
      {
        title: 'POSH policy',
        category: 'POSH',
        requiresAck: true,
        versions: [
          {
            version: 1,
            effectiveFrom: '2026-04-01',
            publishedAt: at('2026-04-01', '11:00'),
            lines: ['Prevention of sexual harassment at the workplace: definitions, the Internal Committee, how to raise a complaint and timelines.'],
          },
        ],
      },
    ];
    const hrId = E(hr);
    let sort = 0;
    for (const p of policies) {
      sort++;
      const policy = await prisma.hrPolicy.create({
        data: { tenantId, title: p.title, category: p.category, requiresAck: p.requiresAck, ackDueDays: 7, status: 'PUBLISHED', holidayYear: p.holidayYear ?? null, sortOrder: sort, createdAt: p.versions[0]!.publishedAt },
      });
      let currentId: string | null = null;
      for (const v of p.versions) {
        const buf = await pdf('Lexisora Infotech · Policies & rulebook', `${p.title}${v.version > 1 ? ` (v${v.version})` : ''}`, [`Effective from ${v.effectiveFrom}.`, ...(v.summary ? [`What changed: ${v.summary}`] : []), ...v.lines]);
        const f = await file(hr, `${p.title} v${v.version}.pdf`, 'policy', false, buf, v.publishedAt);
        const ver = await prisma.hrPolicyVersion.create({
          data: { tenantId, policyId: policy.id, version: v.version, fileId: f.id, effectiveFrom: d(v.effectiveFrom), changeSummary: v.summary ?? null, requiresReack: true, publishedAt: v.publishedAt, publishedByEmployeeId: hrId },
        });
        currentId = ver.id;
        if (!p.requiresAck) continue;
        const pending = new Set((v.pending ?? []).map(E).filter((x): x is string => !!x));
        const acks = pop
          .filter((e) => !e.joiningDate || e.joiningDate.getTime() <= NOW.getTime())
          .filter((e) => !(v.version < p.versions.length && e.joiningDate && e.joiningDate > p.versions[v.version]!.publishedAt)) // joined after the update: only the new version
          .map((e, i) => {
            const from = e.joiningDate && e.joiningDate > v.publishedAt ? e.joiningDate : v.publishedAt;
            const dueAt = v.ackDueAt ?? addMin(from, 7 * 24 * 60);
            const ackAt = pending.has(e.id) ? null : addMin(from, 60 * (6 + ((i * 7) % 60)));
            return { tenantId, policyId: policy.id, policyVersionId: ver.id, employeeId: e.id, dueAt, acknowledgedAt: ackAt && ackAt < NOW ? ackAt : ackAt ? addMin(NOW, -(i + 1) * 45) : null, readSeconds: ackAt ? 90 + ((i * 37) % 400) : null, lastRemindedAt: v.ackDueAt && pending.has(e.id) ? at('2026-09-22', '10:00') : null };
          });
        if (acks.length) await prisma.policyAck.createMany({ data: acks });
      }
      if (currentId) await prisma.hrPolicy.update({ where: { id: policy.id }, data: { currentVersionId: currentId } });
    }
  }
}

// ── Thought of the day ─────────────────────────────────────────────────────

async function seedQuotes(prisma: PrismaClient, tenantId: string) {
  const all: [string, string | null][] = [...WIREFRAME_QUOTES.map((q) => [q, null] as [string, null]), ...CURATED_QUOTES];
  const n = all.length;
  // Rotation index for today; place the wireframe list so that QUOTES[1] lands on it.
  const idx = quoteIndexFor(TODAY, n);
  await prisma.quote.createMany({
    data: all.map(([text, author], k) => ({ tenantId, text, author, active: true, sortOrder: ((k - 1 + idx + n) % n) + 1, createdAt: at('2026-01-02', '09:00') })),
  });
}

// ── Company events ─────────────────────────────────────────────────────────

async function seedEvents(prisma: PrismaClient, tenantId: string, E: (k: string) => string | null) {
  const hr = E('kavya');
  await prisma.companyEvent.createMany({
    data: [
      {
        tenantId,
        title: 'Town hall',
        kind: 'TOWN_HALL',
        description: 'Quarterly business update from Rohit, appraisal timelines and open Q&A. Pune joins on the video bridge.',
        startsAt: at('2026-10-03', '17:00'),
        endsAt: at('2026-10-03', '18:00'),
        location: 'Cafeteria · Ahmedabad HQ',
        audiences: [],
        createdByEmployeeId: hr,
        createdAt: at('2026-09-21', '12:00'),
      },
      {
        tenantId,
        title: 'Security awareness training',
        kind: 'TRAINING',
        description: 'Mandatory one-hour session on phishing and client-data handling (IT & data security policy).',
        startsAt: at('2026-10-14', '11:00'),
        endsAt: at('2026-10-14', '12:00'),
        location: 'Board room',
        audiences: [],
        createdByEmployeeId: hr,
        createdAt: at('2026-09-24', '15:00'),
      },
      {
        tenantId,
        title: 'Diwali celebration & potluck',
        kind: 'CELEBRATION',
        description: 'Families welcome. Sign up for a dish by 1 Nov.',
        startsAt: at('2026-11-08', '16:00'),
        endsAt: at('2026-11-08', '20:00'),
        location: 'Terrace · Ahmedabad HQ',
        audiences: [],
        createdByEmployeeId: hr,
        createdAt: at('2026-09-27', '11:00'),
      },
    ],
  });
}

// ── Personal to-dos (private to their owner) ───────────────────────────────

async function seedTodos(prisma: PrismaClient, tenantId: string, E: (k: string) => string | null) {
  const rows: { who: string; title: string; due?: string; note?: string; done?: Date }[] = [
    { who: 'priya', title: 'Prepare demo notes for the Atlas sprint review', due: '2026-10-02' },
    { who: 'priya', title: 'Update emergency contact in my profile' },
    { who: 'priya', title: 'Share invoice PDF samples with QA', due: '2026-09-28', done: at('2026-09-28', '18:05') },
    { who: 'arjun', title: 'Kestrel go-live checklist', due: '2026-09-30', note: 'Rollback plan + smoke tests with Sneha' },
    { who: 'arjun', title: 'Review Isha’s intern goals', due: '2026-10-01' },
    { who: 'neha', title: 'Prepare Q2 engineering review deck', due: '2026-10-02' },
    { who: 'kavya', title: 'Confirm caterer for the Diwali potluck', due: '2026-10-05' },
    { who: 'kavya', title: 'Collect town hall questions', due: '2026-10-02' },
    { who: 'rohit', title: 'Town hall talking points', due: '2026-10-02' },
    { who: 'sneha', title: 'Plan the billing regression run', due: '2026-10-01' },
  ];
  const data = rows
    .filter((r) => E(r.who))
    .map((r, i) => ({ tenantId, employeeId: E(r.who)!, title: r.title, note: r.note ?? null, dueDate: r.due ? d(r.due) : null, completedAt: r.done ?? null, createdAt: addMin(at('2026-09-25', '09:30'), i * 97) }));
  if (data.length) await prisma.personalTodo.createMany({ data });
}
